name: GitHub Action
run-name: ${{ github.actor }} is testing out GitHub Actions 🚀
on: 
  push: 
  pull_request:
jobs:
  Check_K8s_pods:
    runs-on: ubuntu-latest
    steps:
    - run: |
        echo -e "\n$(kubectl get node)"
        echo -e "\n$(kubectl kubectl get pods -A)\n"

