---
name: remote ssh command
on:
  - push
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: executing remote ssh commands using password
        uses: actions/checkout@v3      
      - name: connect to Kuber and obtaining information about pods
        run: |
          mkdir ~/.ssh
          eval "$(ssh-agent)"
          ssh-add - <<< "${{secrets.SSH_KEY}}"
          ssh "${{ secrets.HOST_USER }}"@"$"{{ secrets.HOST }}"  -o ProxyCommand="ssh -W %h:%p -q "${{secrets.PROXY_USER}}"@"${{secrets.PROXY_SERVER}}" 
          whoami

