name: remote ssh command
on: [push]
jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      id: checks
      run: |
        mkdir ~/.ssh
        eval `ssh-agent -s`
        ssh-add - <<< "${{secrets.SSH_KEY}}"
        ssh -o ProxyCommand="ssh -W %h:%p -q $secrets.PROXY_USER@$secrets.PROXY_SERVER" -L 6443:127.0.0.1:6443 $secrets.HOST_USER@$secrets.HOST -f -N	
        
		
