name: remote ssh command
on: [push]
jobs:

  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
    - name: executing remote ssh commands using password
      id: checks
      uses: appleboy/ssh-action@v0.1.8
      with:
        host: ${{ secrets.HOST }}
        username: ${{ secrets.HOST_USER }}
        password: ${{ secrets.HOST_PASSWORD }}
        port: ${{ secrets.HOST_PORT }}
        proxy_host: ${{ secrets.PROXY_SERVER }}
        proxy_username: ${{ secrets.PROXY_USER }}
        proxy_password: ${{ secrets.PROXY_PASSWORD }}
        run: |
          echo "$(kubectl get pods -A)"
          echo "$(kubectl get pods -A | grep -v Running | grep -v NAMESPACE | wc -l)"
          echo "fail_pods=$(kubectl get pods -A | grep -v Running | grep -v NAMESPACE | wc -l)" >> $GITHUB_OUTPUT
    - name: "Example output call between steps"
      run: |
        echo "Output [${{steps.check.outputs.fail_pods}}]"
    - name: Slack Notification problem
      uses: rtCamp/action-slack-notify@v2
#      if: steps.check.outputs.fail_pods > 1
      env:
          SLACK_TITLE: CI Test Suite
          SLACK_WEBHOOK: ${{ secrets.SLACK_WEBHOOK }}
          SLACK_MESSAGE: ${{ steps.check.outputs.fail_pods }}

